# Generated by Django 4.1.1 on 2022-09-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20220913_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
