# Generated by Django 3.1 on 2022-09-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20220912_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='hidden',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('Python', 'Python'), ('Javascript', 'JavaScript'), ('C++', 'C++')], max_length=30),
        ),
    ]
