# Generated by Django 3.1 on 2022-09-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20220913_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='hidden',
            field=models.BooleanField(),
        ),
    ]
